library(testthat)
library(here)
library(NMF)

test_that("test the function of findNMFRank in benchmarking dataset", {
  e_coli_2_str <- readRDS(here("inst/testdata/findNMFRank", "02X_2str-Escherichia-coli.snmf_r.rds"))
  expect_range(findNMFRank(e_coli_2_str, ncpu = 4), 2)
  e_coli_4_str <- readRDS(here("inst/testdata/findNMFRank", "02X_4str-Escherichia-coli.snmf_r.rds"))
  expect_range(findNMFRank(e_coli_8_str, ncpu = 4), 4)
  e_coli_8_str <- readRDS(here("inst/testdata/findNMFRank", "02X_8str-Escherichia-coli.snmf_r.rds"))
  expect_range(findNMFRank(e_coli_8_str, ncpu = 4), 8)

  bf_4_str <- readRDS(here("inst/testdata/findNMFRank", "Bacteroides-fragilis.snmf_r.rds"))
  expect_range(findNMFRank(bf_4_str, ncpu = 4), 4)
  bl_4_str <- readRDS(here("inst/testdata/findNMFRank", "Bifidobacterium-longum.snmf_r.rds"))
  expect_range(findNMFRank(bl_4_str, ncpu = 4), 4)
  ecl_4_str <- readRDS(here("inst/testdata/findNMFRank", "Enterobacter-cloacae.snmf_r.rds"))
  expect_range(findNMFRank(ecl_4_str, ncpu = 4), 4)
  ef_4_str <- readRDS(here("inst/testdata/findNMFRank", "Enterococcus-Faecalis.snmf_r.rds"))
  expect_range(findNMFRank(ef_4_str, ncpu = 4), 4)
  eco_4_str <- readRDS(here("inst/testdata/findNMFRank", "Escherichia-coli.snmf_r.rds"))
  expect_range(findNMFRank(eco_4_str, ncpu = 4), 4)
  fp_4_str <- readRDS(here("inst/testdata/findNMFRank", "Faecalibacterium-prausnitzii.snmf_r.rds"))
  expect_range(findNMFRank(fp_4_str, ncpu = 4), 4)
  pc_4_str <- readRDS(here("inst/testdata/findNMFRank", "Prevotella-copri.snmf_r.rds"))
  expect_range(findNMFRank(pc_4_str, ncpu = 4), 4)
  sa_4_str <- readRDS(here("inst/testdata/findNMFRank", "Staphylococcus-aureus.snmf_r.rds"))
  expect_range(findNMFRank(sa_4_str, ncpu = 4), 4)
  sp_4_str <- readRDS(here("inst/testdata/findNMFRank", "Streptococcus-pneumoniae.snmf_r.rds"))
  expect_range(findNMFRank(sp_4_str, ncpu = 4), 4)

  fmt_4_str <- readRDS(here("inst/testdata/findNMFRank", "fmt-Faecalibacterium-prausnitzii.snmf_r.rds"))
  expect_range(findNMFRank(fmt_6_str, ncpu = 4), 6)
})
